FROM ros:humble-ros-base-jammy
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential cmake git python3-pip python3-colcon-common-extensions \
    python3-rosdep python3-vcstool python3-jsonschema python3-rfc3339-validator python3-yaml \
    libunwind-dev ros-humble-gazebo-ros-pkgs ros-humble-robot-localization \
    ros-humble-navigation2 ros-humble-nav2-bringup ros-humble-ros2-control \
    ros-humble-ros2-controllers ros-humble-rosbag2-storage-mcap \
    && rm -rf /var/lib/apt/lists/*
RUN python3 -m pip install jsonschema==4.26.0 rfc3339-validator==0.1.4 PyYAML==6.0.3
WORKDIR /workspaces/mars-rover-prop-m-blueprint
COPY --chmod=755 infrastructure/docker/scripts/entrypoint_ros.sh /entrypoint_ros.sh
ENTRYPOINT ["/entrypoint_ros.sh"]
CMD ["bash"]
